# Generated by Django 4.2.3 on 2023-07-26 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 2, 11, 53, 25, 609370)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
