# Generated by Django 4.2.3 on 2023-07-26 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_list", "0002_task_deadline_alter_task_is_done"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="task",
            name="name",
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 2, 11, 58, 34, 438247)
            ),
        ),
    ]
